# Generated by Django 3.1.7 on 2021-07-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=150)),
                ('phoneno', models.BigIntegerField()),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
            ],
        ),
    ]
